### ISSUE TITLE
Module Won't Install

### ISSUE THREAD

**Issue by cryptixcoder** [typefoo/node-shipping-usps#1]
![screen shot 2015-04-30 at 3 59 04 pm](https://cloud.githubusercontent.com/assets/1449957/7421371/ec60c098-ef51-11e4-8a3c-6bd00d999cd4.png)

**Comment by jjosef** [comment]
Thanks for testing this on v0.12.x, just updated it and released v0.0.4 which should fix your issue

**Comment by cryptixcoder** [comment]
Worked great, Thanks!!
